esphome:
  name: esp-cvnet
  friendly_name: esp-cvnet

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "mxtvcMZKTcHBBIyVJG9YEPZOBqLk/Kd6Mw8K1NMNRdE="

uart:
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_pin: GPIO1
  tx_pin: GPIO2

external_components:
  - source: github://shqns123/espcomponents@master
    components: [uartex]
    refresh: always

uartex:
  rx_timeout: 10ms
  tx_delay: 50ms
  tx_timeout: 500ms
  tx_retry_cnt: 3
  rx_header: [0xF7]
  tx_header: [0xF7]
  rx_footer: [0xAA]
  tx_footer: [0xAA]
  version:
    disabled: False
  error:
    disabled: False
  log:
    disabled: False

# --- 스위치 (조명) ---
switch:
  - platform: uartex
    name: "Room 0 Light 1"
    state:
      data: [0x20, 0x01, 0x21]
    state_on:
      offset: 4
      data: [0x01]
    state_off:
      offset: 4
      data: [0x00]
    command_on:
      data: [0x20, 0x21, 0x01, 0x11, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x56]
      ack: [0x20, 0x01, 0x21, 0x9F]
    command_off:
      data: [0x20, 0x21, 0x01, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x53]
      ack: [0x20, 0x01, 0x21, 0x9F]

  - platform: uartex
    name: "Room 0 Light 2"
    state:
      data: [0x20, 0x01, 0x21]
    state_on:
      offset: 5
      data: [0x01]
    state_off:
      offset: 5
      data: [0x00]
    command_on:
      data: [0x20, 0x21, 0x01, 0x12, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x55]
      ack: [0x20, 0x01, 0x21, 0x9F]
    command_off:
      data: [0x20, 0x21, 0x01, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x54]
      ack: [0x20, 0x01, 0x21, 0x9F]

  - platform: uartex
    name: "Room 0 Light 3"
    state:
      data: [0x20, 0x01, 0x21]
    state_on:
      offset: 6
      data: [0x01]
    state_off:
      offset: 6
      data: [0x00]
    command_on:
      data: [0x20, 0x21, 0x01, 0x13, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x56]
      ack: [0x20, 0x01, 0x21, 0x9F]
    command_off:
      data: [0x20, 0x21, 0x01, 0x13, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x55]
      ack: [0x20, 0x01, 0x21, 0x9F]

