esphome:
  name: esp-cvnet
  friendly_name: esp-cvnet

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "mxtvcMZKTcHBBIyVJG9YEPZOBqLk/Kd6Mw8K1NMNRdE="

uart:
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_pin: GPIO1
  tx_pin: GPIO2

external_components:
  - source: github://shqns123/espcomponents@master
    components: [uartex]
    refresh: always

uartex:
  rx_timeout: 10ms
  tx_delay: 50ms
  tx_timeout: 500ms
  tx_retry_cnt: 3
  rx_header: [0xF7]
  tx_header: [0xF7]
  rx_footer: [0xAA]
  tx_footer: [0xAA]
  rx_checksum: xor_add
  tx_checksum: xor_add
  version:
    disabled: False
  error:
    disabled: False
  log:
    disabled: False

# --- 스위치 (조명) ---
switch:
  - platform: uartex
    name: "Room 0 Light 1"
    state:
      data: [0x20, 0x01, 0x21]
    state_on:
      offset: 4
      data: [0x01]
    state_off:
      offset: 4
      data: [0x00]
    command_on:
      data: [0x20, 0x21, 0x01, 0x11, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x21, 0x9F]
    command_off:
      data: [0x20, 0x21, 0x01, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x21, 0x9F]

  - platform: uartex
    name: "Room 0 Light 2"
    state:
      data: [0x20, 0x01, 0x21]
    state_on:
      offset: 5
      data: [0x01]
    state_off:
      offset: 5
      data: [0x00]
    command_on:
      data: [0x20, 0x21, 0x01, 0x12, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x21, 0x9F]
    command_off:
      data: [0x20, 0x21, 0x01, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x21, 0x9F]

  - platform: uartex
    name: "Room 0 Light 3"
    state:
      data: [0x20, 0x01, 0x21]
    state_on:
      offset: 6
      data: [0x01]
    state_off:
      offset: 6
      data: [0x00]
    command_on:
      data: [0x20, 0x21, 0x01, 0x13, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x21, 0x9F]
    command_off:
      data: [0x20, 0x21, 0x01, 0x13, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x21, 0x9F]

# --- 팬 (환기) ---
fan:
  - platform: uartex
    name: "Air Fan"
    speed_cnt: 4
    state:
      data: [0x20, 0x01, 0x7A]
    state_on:
      offset: 7
      data: [0x0F]
    state_off:
      offset: 7
      data: [0x00]
    state_speed:
      offset: 4
      signed: False
    command_on:
      data: [0x20, 0x7A, 0x01, 0x11, 0x22, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x7A, 0x91]
    command_off:
      data: [0x20, 0x7A, 0x01, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x7A, 0x91]
    command_speed: !lambda |-
      uint8_t mode;
      if (x <= 25) {
        mode = 0x21;
      } else if (x <= 50) {
        mode = 0x22;
      } else if (x <= 75) {
        mode = 0x23;
      } else {
        mode = 0x03;
      }
      return {{0x20, 0x7A, 0x01, 0x11, mode, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
              {0x20, 0x01, 0x7A, 0x91}};

# --- 난방기 (온도조절) ---
climate:
  - platform: uartex
    name: "Heater 1"
    id: heater_1
    visual:
      min_temperature: 6 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state:
      data: [0x20, 0x01, 0x4A]
    state_temperature_current:
      offset: 5
    state_temperature_target: !lambda |-
      return ((uint8_t)data[4] & 0x7F);
    state_off:
      offset: 4
      data: [0x80]
    state_heat:
      offset: 4
      data: [0x80]
    command_off: !lambda |-
      uint8_t target = id(heater_1).target_temperature;
      return {{0x20, 0x41, 0x01, 0x11, target, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
              {0x20, 0x01, 0x41, 0x91}};
    command_heat: !lambda |-
      uint8_t target = id(heater_1).target_temperature;
      return {{0x20, 0x41, 0x01, 0x11, (uint8_t)(target + 0x80), 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
              {0x20, 0x01, 0x41, 0x91}};
    command_temperature: !lambda |-
      uint8_t target = x;
      return {{0x20, 0x41, 0x01, 0x11, (uint8_t)(target + 0x80), 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
              {0x20, 0x01, 0x41, 0x91}};

# 나머지 Heater 2~4도 Heater 1 복붙해서 id만 heater_2, heater_3, heater_4로 맞춰주면 돼.
