esphome:
  name: esp-cvnet
  friendly_name: esp-cvnet

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

logger:

api:
  encryption:
    key: "mxtvcMZKTcHBBIyVJG9YEPZOBqLk/Kd6Mw8K1NMNRdE="

uart:
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_pin: GPIO1
  tx_pin: GPIO2

  
external_components:
  - source: github://shqns123/espcomponents@master
    components: [uartex]
    refresh: always

uartex:
  rx_timeout: 100ms
  tx_delay: 50ms
  tx_timeout: 1000ms
  tx_retry_cnt: 3
  rx_header: [0xF7]
  tx_header: [0xF7]
  rx_footer: [0xAA]
  tx_footer: [0xAA]
  rx_checksum: add_no_header
  tx_checksum: add_no_header
  
  version:
    disabled: False
  error:
    disabled: False
  log:
    disabled: True

#작성중
switch:
  - platform: uartex
    name: "Living 1"
    state: 
      data: [0x20, 0x01, 0x21, 0x81]
    state_on:
      offset: 4
      data: [0x01]
    state_off:
      offset: 4
      data: [0x00]
    command_on: 
      data: [0x20, 0x21, 0x01, 0x11, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x21, 0x9F]
    command_off:
      data: [0x20, 0x21, 0x01, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x21, 0x9F]

  - platform: uartex
    name: "Living 2"
    state: 
      data: [0x20, 0x01, 0x21, 0x81]
    state_on:
      offset: 5
      data: [0x01]
    state_off:
      offset: 5
      data: [0x00]
    command_on: 
      data: [0x20, 0x21, 0x01, 0x12, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x21, 0x9F]
    command_off:
      data: [0x20, 0x21, 0x01, 0x12, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x21, 0x9F]

  - platform: uartex
    name: "Living 3"
    state: 
      data: [0x20, 0x01, 0x21, 0x81]
    state_on:
      offset: 6
      data: [0x01]
    state_off:
      offset: 6
      data: [0x00]
    command_on: 
      data: [0x20, 0x21, 0x01, 0x13, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x21, 0x9F]
    command_off:
      data: [0x20, 0x21, 0x01, 0x13, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x21, 0x9F]


fan:
  - platform: uartex
    name: "Air Fan"
    speed_cnt: 4
    state:
      data: [0x20, 0x01, 0x7A]
    state_on:
      offset: 7
      data: [0x0F]
    state_off:
      offset: 7
      data: [0x00]
    command_on:
      data: [0x20, 0x7A, 0x01, 0x11, 0x21, 0x00, 0x00, 0x0F, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x7A, 0x91]
    command_off:
      data: [0x20, 0x7A, 0x01, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x20, 0x01, 0x7A, 0x91]
    command_speed: !lambda |-
      uint8_t speed = x;
      uint8_t packet_speed;
      if (speed == 1) {
        packet_speed = 0x21;
      } else if (speed == 2) {
        packet_speed = 0x22;
      } else if (speed == 3) {
        packet_speed = 0x23;
      } else if (speed == 4) {
        packet_speed = 0x03;
      } else {
        packet_speed = 0x21;  // 기본 fallback
      }
      return {{0x20, 0x7A, 0x01, 0x11, packet_speed, 0x00, 0x00, 0x0F, 0x00, 0x00, 0x00, 0x00},{0x20, 0x01, 0x7A, 0x91}};

    state_speed:
      offset: 4
      signed: False



climate:
  - platform: uartex
    name: Living heat"
    id: heater_1
    visual:
      min_temperature: 14 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state:
      data: [0x20, 0x01, 0x4A]
    state_temperature_current:
      offset: 5
    state_temperature_target: !lambda |-
      return ((uint8_t)data[4] & 0x7F);
    state_off:
      offset: 4
      data: [0x80]
    state_heat:
      offset: 4
      data: [0x80]
    command_off: !lambda |-
      uint8_t target = id(heater_1).target_temperature;
      return {{0x20, 0x41, 0x01, 0x11, target, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
              {0x20, 0x01, 0x41, 0x91}};
    command_heat: !lambda |-
      uint8_t target = id(heater_1).target_temperature;
      return {{0x20, 0x41, 0x01, 0x11, (uint8_t)(target + 0x80), 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
              {0x20, 0x01, 0x41, 0x91}};
    command_temperature: !lambda |-
      uint8_t target = x;
      return {{0x20, 0x41, 0x01, 0x11, (uint8_t)(target + 0x80), 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
              {0x20, 0x01, 0x41, 0x91}};

  - platform: uartex
    name: "Bedroom heat"
    id: heater_2
    visual:
      min_temperature: 14 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state:
      data: [0x20, 0x01, 0x4A]
    state_temperature_current:
      offset: 7
    state_temperature_target: !lambda |-
      return ((uint8_t)data[6] & 0x7F);
    state_off:
      offset: 6
      data: [0x80]
    state_heat:
      offset: 6
      data: [0x80]
    command_off: !lambda |-
      uint8_t target = id(heater_2).target_temperature;
      return {{0x20, 0x42, 0x01, 0x11, target, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
              {0x20, 0x01, 0x42, 0x91}};
    command_heat: !lambda |-
      uint8_t target = id(heater_2).target_temperature;
      return {{0x20, 0x42, 0x01, 0x11, (uint8_t)(target + 0x80), 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
              {0x20, 0x01, 0x42, 0x91}};
    command_temperature: !lambda |-
      uint8_t target = x;
      return {{0x20, 0x42, 0x01, 0x11, (uint8_t)(target + 0x80), 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
              {0x20, 0x01, 0x42, 0x91}};

  - platform: uartex
    name: "Babyroom heat"
    id: heater_3
    visual:
      min_temperature: 14 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state:
      data: [0x20, 0x01, 0x4A]
    state_temperature_current:
      offset: 9
    state_temperature_target: !lambda |-
      return ((uint8_t)data[8] & 0x7F);
    state_off:
      offset: 8
      data: [0x80]
    state_heat:
      offset: 8
      data: [0x80]
    command_off: !lambda |-
      uint8_t target = id(heater_3).target_temperature;
      return {{0x20, 0x43, 0x01, 0x11, target, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
              {0x20, 0x01, 0x43, 0x91}};
    command_heat: !lambda |-
      uint8_t target = id(heater_3).target_temperature;
      return {{0x20, 0x43, 0x01, 0x11, (uint8_t)(target + 0x80), 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
              {0x20, 0x01, 0x43, 0x91}};
    command_temperature: !lambda |-
      uint8_t target = x;
      return {{0x20, 0x43, 0x01, 0x11, (uint8_t)(target + 0x80), 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
              {0x20, 0x01, 0x43, 0x91}};

  - platform: uartex
    name: "pcroom heat"
    id: heater_4
    visual:
      min_temperature: 14 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state:
      data: [0x20, 0x01, 0x4A]
    state_temperature_current:
      offset: 11
    state_temperature_target: !lambda |-
      return ((uint8_t)data[10] & 0x7F);
    state_off:
      offset: 10
      data: [0x80]
    state_heat:
      offset: 10
      data: [0x80]
    command_off: !lambda |-
      uint8_t target = id(heater_4).target_temperature;
      return {{0x20, 0x44, 0x01, 0x11, target, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
              {0x20, 0x01, 0x44, 0x91}};
    command_heat: !lambda |-
      uint8_t target = id(heater_4).target_temperature;
      return {{0x20, 0x44, 0x01, 0x11, (uint8_t)(target + 0x80), 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
              {0x20, 0x01, 0x44, 0x91}};
    command_temperature: !lambda |-
      uint8_t target = x;
      return {{0x20, 0x44, 0x01, 0x11, (uint8_t)(target + 0x80), 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00},
              {0x20, 0x01, 0x44, 0x91}};
